### ISSUE TITLE
Weight config does't work

### ISSUE THREAD

**Issue by HightOracle** [RazrabGit/SchoolDungeon#10]
Interior weight on different moons doesn't work. It sets defaul value for all listed moons (in logs during mod loading)

**Comment by RazrabGit** [comment]
weird, everything works fine for me. Did you restart the game after applying the config, and did you enter the moons and weights for them correctly into the config?

**Comment by HightOracle** [comment]
Shold've send log screenshots right away.
![image](https://github.com/RazrabGit/SchoolDungeon/assets/160997284/56d15caf-d436-4fde-80dc-0f461c28837f)
This is what I see in logs

For example, here's MentalHospital's logs. And it sets right values.
![изображение_2024-05-09_212219069](https://github.com/RazrabGit/SchoolDungeon/assets/160997284/6b75ff72-0d8a-4696-9beb-1fbc8c47c382)


P.S. MentalHospital values definitly work, I run into this interior 8 times of 10 on Solace

**Comment by RazrabGit** [comment]
i'll check it, but later, not much time

**Comment by RazrabGit** [comment]
This is a visual problem (this is only displayed in the console), everything works in the game. But thank you for noticing, I'll fix it in the next patch

**Comment by HightOracle** [comment]
Ok, thank you

пн, 13 мая 2024 г., 23:20 RazrabGit ***@***.***>:
