### ISSUE TITLE
School dungeon cannot spawn outside of School moon

### ISSUE THREAD

**Issue by Blastinburn** [RazrabGit/SchoolDungeon#11]
Loading up no other mods the school dungeon will not show up as a possible dungeon using LLL's simulate function.

Enabling custom configuration in the LLL config and manually setting moons, such as Offense:999, All:9999, or Vanilla:9999 will result in being unable to load any save files, selecting a file will leave the player on the file select screen.

Additionally I took a look at the LLL config afterwards and it looks like the settings for every dungeon flow have been invalidated, all comments and setting information have been removed from the config leaving it with only text entry values, something I have seen before usually when a mod update changes the configuration for the mod and old config data is left in the file.
![image](https://github.com/user-attachments/assets/83f4bf28-fb11-4d30-a6dd-71798e55f12c)

If I do not touch any configuration options the school dungeon can spawn at the MAOY school but nowhere else.

**Comment by RazrabGit** [comment]
Maybe something happened when I updated LLL in the editor to a new version. I'll take a look a bit later, I'll try to fix it soon.
