### ISSUE TITLE
Doors in multiplayer

### ISSUE THREAD

**Issue by Qugar** [RazrabGit/SchoolDungeon#4]
The doors do not open for other players in multiplayer, everyone has to open each door themselves.

**Comment by RazrabGit** [comment]
okay, i'll check this and fix in the next patch.

**Comment by Qugar** [comment]
Thank you very much. I love the moon and the interior. Keep up the good work. :thumbsup:

**Comment by RazrabGit** [comment]
thanks)

**Comment by Qugar** [comment]
Unfortunately the doors are still not synchronized in multiplayer.

**Comment by RazrabGit** [comment]
This issue will be the main target in the next patch
