### ISSUE TITLE
Only the default internal map appears.

### ISSUE THREAD

**Issue by pil0lo** [RazrabGit/SchoolDungeon#7]
New maps are not applied.
Only the default indoor interior map continues to appear.
I don't know what the problem is.

**Comment by RazrabGit** [comment]
i'll check it later

**Comment by RazrabGit** [comment]
thats weird, new maps in a config are applying for me. maybe you did something wrong in config?

**Comment by pil0lo** [comment]
First of all, I uploaded it as code.
I am using this mode.

018ec7f4-6170-3fd1-6ce0-82bef2f55fb1

**Comment by RazrabGit** [comment]
it's not a mod problem. you just need to know that "Lethal Level Loader Fixed" and the default LLL should not be enabled at the same time. either "Lethal Level Loader Fixed" or the default LLL should be enabled.

**Comment by RazrabGit** [comment]
I think you should close this issue that you opened in other interiors.

**Comment by pil0lo** [comment]
Are you saying that “LethalLevelLoader” and “LethalLevelLoaderFixed” mods cannot be used together???
If you only use "LethalLevelLoader" mode, an error will appear when entering the game, so "LethalLevelLoaderFixed" mode was added to eliminate the error.
When I used only this mode, "LethalLevelLoader", it didn't seem to appear...???
  Is “LethalLevelLoaderFixed” the only mod that needs to be included?
