### ISSUE TITLE
spray paint isnt useable

### ISSUE THREAD

**Issue by VirusTLNR** [RazrabGit/SchoolDungeon#8]
afaik last i tested, spray paint does not stick to the walls, so you cant use spray paint, at least not on the majority of this interior, might be the same for your moon too, but didnt check.

also, i beleive you unlocked a second fire exit in a recent update, the readme still says it has one.

otherwise, love your moon <3

**Comment by RazrabGit** [comment]
Perhaps you tested my dungeon on that moon where spray paint itself doesn't work. Or you haven't updated the mods to the latest versions. When I tested on my moon and dungeon, the spray paint worked as it should.

**Comment by VirusTLNR** [comment]
I will recheck.. but last time I tried it didn't work.

Edit- everything was up to date though, and I only use your interior on your moon.

**Comment by RazrabGit** [comment]
Doesn’t it work only in a specific place, or generally at all levels, both in the interior and on the moon? If so, then maybe the problem is not entirely in my mod, but I honestly have no assumptions, everything works for me

**Comment by VirusTLNR** [comment]
sorry, to my chagrin, i didnt recheck. i will try to remember to do so tomorrow and let you know when i remember to any spots that cant be painted :)
